"""
export.py – Report and CSV export utilities.
"""
import pandas as pd
import io


def export_processed_csv(df):
    """Returns a CSV string of the full processed DataFrame."""
    return df.to_csv(index=False)


def export_risk_list(df):
    """Returns a CSV string of only at-risk students."""
    risk_df = df[df['final_risk'].isin(['High Risk', 'Medium Risk'])]
    cols = [c for c in ['name', 'class', 'avg_percentage', 'attendance',
                        'risk_score', 'final_risk', 'risk_reasons'] if c in risk_df.columns]
    # Fallback: if mapped column names differ, just export all
    if not cols:
        return risk_df.to_csv(index=False)
    return risk_df[cols].to_csv(index=False)


def generate_summary_report(df, mapping, subjects):
    """Generates a human-readable text summary report."""
    lines = []
    lines.append("=" * 60)
    lines.append("     EDURISK AI — Student Performance Summary Report")
    lines.append("=" * 60)
    lines.append("")

    total = len(df)
    high = len(df[df['final_risk'] == 'High Risk'])
    medium = len(df[df['final_risk'] == 'Medium Risk'])
    low = len(df[df['final_risk'] == 'Low Risk'])

    lines.append(f"Total Students Analyzed : {total}")
    lines.append(f"High Risk               : {high}  ({high/total*100:.1f}%)")
    lines.append(f"Medium Risk             : {medium}  ({medium/total*100:.1f}%)")
    lines.append(f"Low Risk                : {low}  ({low/total*100:.1f}%)")
    lines.append("")

    # Subject averages
    lines.append("--- Subject-wise Average Scores ---")
    for sub in subjects:
        pct_col = f"{sub}_pct"
        if pct_col in df.columns:
            avg = df[pct_col].mean()
            lines.append(f"  {sub:20s} : {avg:.1f}%")
    lines.append("")

    # Attendance
    att_col = mapping.get('attendance')
    if att_col and att_col in df.columns:
        lines.append(f"Average Attendance      : {df[att_col].mean():.1f}%")
        lines.append("")

    # Top at-risk students
    lines.append("--- Top At-Risk Students ---")
    risk_df = df[df['final_risk'] == 'High Risk'].sort_values('risk_score', ascending=False).head(10)
    name_col = mapping.get('name', 'name')
    for _, row in risk_df.iterrows():
        name = row.get(name_col, 'Unknown')
        lines.append(f"  • {name} — Risk Score: {row.get('risk_score', 'N/A')} | {row.get('risk_reasons', '')}")

    lines.append("")
    lines.append("=" * 60)
    lines.append("Report generated by EDURISK AI")
    lines.append("=" * 60)

    return "\n".join(lines)
